import React, { useState, useEffect } from 'react';
import { db } from '../firebase/config';
import { collection, getDocs } from 'firebase/firestore';

const Transactions = () => {
  const [groupedInvoices, setGroupedInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');

  useEffect(() => {
    const fetchTransactions = async () => {
      try {
        const querySnapshot = await getDocs(collection(db, 'transactions'));
        const data = querySnapshot.docs.map(doc => doc.data());

        const groups = {};
        
        data.forEach(t => {
          if (t.type === 'OUT') { 
            if (!groups[t.invoiceNo]) {
              groups[t.invoiceNo] = {
                invoiceNo: t.invoiceNo,
                date: t.date,
                customer: t.customer,
                totalAmount: 0,
                items: []
              };
            }
            groups[t.invoiceNo].items.push(t);
            groups[t.invoiceNo].totalAmount += t.total;
          }
        });

        const sortedGroups = Object.values(groups).sort((a, b) => new Date(b.date) - new Date(a.date));
        
        setGroupedInvoices(sortedGroups);
        setLoading(false);
      } catch (error) {
        console.error("Error fetching transactions: ", error);
        setLoading(false);
      }
    };

    fetchTransactions();
  }, []);

  const fmt = (num) => Number(num).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  // 🚀 UPGRADE 3 (FIXED): Naa nay "Unod" (Table Breakdown) ang Daily Report
  const printDailyReport = () => {
    const todayStr = new Date().toLocaleDateString('en-PH', { month: '2-digit', day: '2-digit', year: 'numeric' });
    
    const todaySales = groupedInvoices.filter(g => g.date === todayStr);
    const totalGross = todaySales.reduce((sum, g) => sum + g.totalAmount, 0);

    const w = window.open('', '_blank', 'width=800,height=800'); // Gipadak-an nato gamay ang window para sa table
    w.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        @page { margin: 15mm; size: auto; }
        body { font-family: Arial, sans-serif; font-size: 11pt; padding: 10px; color: #333; }
        h2 { text-align: center; margin-bottom: 5px; }
        .subtitle { text-align: center; font-size: 10pt; color: #666; margin-bottom: 20px; }
        .line { border-bottom: 2px solid black; margin: 15px 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 10pt; }
        th, td { border-bottom: 1px solid #ddd; padding: 10px 8px; text-align: left; }
        th { border-bottom: 2px solid black; font-weight: bold; }
        .right { text-align: right; }
        .summary-box { margin-top: 20px; border-top: 2px solid black; padding-top: 15px; display: flex; justify-content: space-between; align-items: center; }
      </style>
    </head>
    <body>
      <h2>END OF DAY SALES REPORT</h2>
      <div class="subtitle">Date: ${todayStr}</div>
      
      <table>
        <thead>
          <tr>
            <th style="width: 20%;">Invoice No</th>
            <th style="width: 45%;">Customer</th>
            <th style="width: 15%; text-align: center;">Items</th>
            <th style="width: 20%;" class="right">Amount</th>
          </tr>
        </thead>
        <tbody>
          ${todaySales.length === 0 ? `<tr><td colSpan="4" style="text-align:center;">No transactions for today.</td></tr>` : ''}
          ${todaySales.map(inv => `
            <tr>
              <td style="font-family: monospace; font-weight: bold;">${inv.invoiceNo}</td>
              <td>${inv.customer}</td>
              <td style="text-align: center;">${inv.items.length}</td>
              <td class="right" style="color: green; font-weight: bold;">P ${fmt(inv.totalAmount)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="summary-box">
        <div style="font-size: 12pt;"><b>Total Invoices:</b> ${todaySales.length}</div>
        <div style="font-size: 16pt;"><b>Gross Sales:</b> P ${fmt(totalGross)}</div>
      </div>
      
      <p style="font-size: 9pt; margin-top: 50px; text-align: center; color: #888;">Generated by GV POS System</p>
      
      <script>window.onload = () => { window.print(); window.close(); }</script>
    </body>
    </html>
    `);
    w.document.close();
  };

  // 🚀 UPGRADE 4 (FIXED): Tinangtang na ang "REPRINT" nga watermark
  const reprintInvoice = (inv) => {
    const subtotal = inv.totalAmount;
    const vat = subtotal / 1.12 * 0.12;
    const netOfVat = subtotal - vat;

    const w = window.open('', '_blank', 'width=800,height=1000');
    w.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        @page { margin: 0; size: Letter portrait; }
        body { font-family: Arial, sans-serif; font-size: 10pt; margin: 0; padding: 0; position: relative; width: 100%; height: 100%; overflow: hidden; }
        .data { position: absolute; white-space: nowrap; overflow: hidden; font-weight: bold; }
      </style>
    </head>
    <body>
      <div class="data" style="top: 49mm; left: 45mm; width: 110mm;">${inv.customer}</div>
      <div class="data" style="top: 61mm; left: 45mm; width: 110mm;">DAVAO CITY</div>
  
      <div class="data" style="top: 36mm; left: 162mm;">${inv.date}</div>
      <div class="data" style="top: 43mm; left: 165mm;">30DAYS</div>
  
      ${inv.items.map((item, idx) => {
        const currentTop = 83 + (idx * 6.5);
        return `
          <div class="data" style="top: ${currentTop}mm; left: 15mm; width: 85mm;">${item.description}</div>
          <div class="data" style="top: ${currentTop}mm; left: 108mm; width: 15mm; text-align: center;">${item.qty}</div>
          <div class="data" style="top: ${currentTop}mm; left: 125mm; width: 20mm; text-align: right;">${fmt(item.price)}</div>
          <div class="data" style="top: ${currentTop}mm; left: 155mm; width: 25mm; text-align: right;">${fmt(item.total)}</div>
        `;
      }).join('')}
  
      <div class="data" style="top: 223mm; left: 165mm; width: 25mm; text-align: right;">${fmt(subtotal)}</div>
      <div class="data" style="top: 229mm; left: 165mm; width: 25mm; text-align: right;">${fmt(vat)}</div>
      <div class="data" style="top: 235mm; left: 165mm; width: 25mm; text-align: right;">${fmt(netOfVat)}</div>
      <div class="data" style="top: 259mm; left: 165mm; width: 25mm; text-align: right; font-size: 12pt;">${fmt(subtotal)}</div>
  
      <script>window.onload = () => { window.print(); window.close(); }</script>
    </body>
    </html>
    `);
    w.document.close();
  };

  const filteredInvoices = groupedInvoices.filter(inv => 
    inv.invoiceNo.toLowerCase().includes(searchQuery.toLowerCase()) || 
    inv.customer.toLowerCase().includes(searchQuery.toLowerCase()) ||
    inv.date.includes(searchQuery)
  );

  return (
    <div className="card">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--border)', paddingBottom: '12px', marginBottom: '16px' }}>
        <div className="card-title" style={{ borderBottom: 'none', paddingBottom: 0, marginBottom: 0 }}>
          Transaction Archives
        </div>
        
        <div style={{ display: 'flex', gap: '10px' }}>
          <button onClick={printDailyReport} style={{ padding: '8px 15px', background: 'var(--primary)', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: 'bold' }}>
            📄 Print Daily Report
          </button>
          
          <input 
            type="text" 
            placeholder="🔍 Search date, invoice, or customer..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            style={{ padding: '8px 12px', borderRadius: '6px', background: 'var(--bg)', border: '1px solid var(--border2)', color: 'white', width: '280px', outline: 'none' }}
          />
        </div>
      </div>

      {loading ? (
        <div style={{ padding: '30px', color: 'var(--text2)', textAlign: 'center' }}>Loading transactions... ⏳</div>
      ) : (
        <div className="table-wrap">
          <table style={{ width: '100%', textAlign: 'left', borderCollapse: 'collapse' }}>
            <thead>
              <tr style={{ borderBottom: '1px solid var(--border)', color: 'var(--text3)' }}>
                <th style={{ padding: '12px 8px' }}>Date</th>
                <th style={{ padding: '12px 8px' }}>Invoice No</th>
                <th style={{ padding: '12px 8px' }}>Customer</th>
                <th style={{ padding: '12px 8px', textAlign: 'center' }}>Items Count</th>
                <th style={{ padding: '12px 8px', textAlign: 'right' }}>Total Amount</th>
                <th style={{ padding: '12px 8px', textAlign: 'right' }}>Action</th>
              </tr>
            </thead>
            <tbody>
              {filteredInvoices.length === 0 ? (
                <tr><td colSpan="6" style={{ textAlign: 'center', padding: '20px', color: 'var(--text2)' }}>No transactions found.</td></tr>
              ) : (
                filteredInvoices.map((inv) => (
                  <tr key={inv.invoiceNo} style={{ borderBottom: '1px solid var(--border)' }}>
                    <td style={{ padding: '12px 8px', fontSize: '13px' }}>{inv.date}</td>
                    <td style={{ padding: '12px 8px', fontFamily: 'monospace', color: 'var(--blue)' }}>{inv.invoiceNo}</td>
                    <td style={{ padding: '12px 8px', fontWeight: '500' }}>{inv.customer}</td>
                    <td style={{ padding: '12px 8px', textAlign: 'center', color: 'var(--text2)' }}>{inv.items.length} item(s)</td>
                    <td style={{ padding: '12px 8px', textAlign: 'right', fontWeight: 'bold', color: 'var(--green)' }}>
                      ₱{fmt(inv.totalAmount)}
                    </td>
                    <td style={{ padding: '12px 8px', textAlign: 'right' }}>
                      <button onClick={() => reprintInvoice(inv)} style={{ padding: '6px 12px', background: 'var(--surface2)', color: 'white', border: '1px solid var(--border2)', borderRadius: '4px', cursor: 'pointer', fontSize: '12px' }}>
                        🖨️ Reprint SI
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default Transactions;